#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';
include __DIR__.'/GenerateModule.class.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new GenerateModuleCommand());

$application->run();
